services:
  app:
    container_name: grain-pay-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: local
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://db:5432/grain-pay-local
      POSTGRES_DATASOURCE_USERNAME: postgres
      POSTGRES_DATASOURCE_PASSWORD: password
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
  db:
    container_name: grain-pay-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: grain-pay-local
    ports:
      - "5432:5432"
