spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_DATASOURCE_USERNAME}
    password: ${POSTGRES_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
  application:
    name: grain-pay-api
  flyway:
    enabled: true
server:
  port: ${PORT}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
notification:
  mail:
    from: ${MAIL_FROM:noreply@grainpay.dev}
spring:
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true